# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3cae2a5e465516176bec11e67d2f0a7cd1682fa7adad014ddcf0244a19b5569ce1115232bdb5ba108832e11120926994e8548c69446e9433ed505533c88d479

test:
  secret_key_base: d2717f15fec378cd43e24b36830e41a7b7e0c8296a22c2721ab234d31e53c35689c23de261d68800a6e17a7ffabf44545463acaa921cc6d523badedeed741d60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
